branches:
  - main
  - name: beta
    prerelease: true

plugins:
    - - "@semantic-release/commit-analyzer"
      - preset: "conventionalcommits"
        releaseRules:
          - type: "docs"
            release: "patch"
          - type: "refactor"
            release: "patch"
          - type: "style"
            release: "patch"
          - type: "ci"
            release: "patch"
          - type: "test"
            release: "patch"
          - type: "build"
            release: "patch"
          - type: "perf"
            release: "patch"
          - type: "chore"
            release: "patch"
          - type: "fix"
            release: "patch"
          - type: "feat"
            release: "minor"
          - type: "BREAKING CHANGE"
            release: "major"

    - - "@semantic-release/release-notes-generator"
      - preset: "conventionalcommits"

    - - "@semantic-release/github":
      - assets:
          - path: "dist/*.whl"
            label: "Wheel Package"
          - path: "dist/*.tar.gz"
            label: "Source Package"

    - "@semantic-release/changelog"

    - "@semantic-release-pypi"
