branches:
  - main
  - name: beta
    prerelease: true

plugins:
    - - "@semantic-release/commit-analyzer"
      - preset: "conventionalcommits"
        releaseRules:
          - type: "fix"
            release: "patch"
          - type: "feat"
            release: "minor"
          - type: "perf"
            release: "minor"            
          - type: "BREAKING CHANGE"
            release: "major"

    - - "@semantic-release/release-notes-generator"
      - preset: "conventionalcommits"
        parserOpts:
          types:
            - type: feat
              section: "Features"
            - type: fix
              section: "Bug Fixes"
            - type: chore
              hidden: true
            - type: docs
              hidden: true         
            - type: style
              hidden: true
            - type: refactor
              hidden: true
            - type: perf
              hidden: true
            - type: test
              hidden: true
            - type: ci
              hidden: true
                                                        
    - - "@semantic-release/github":
      - assets:
          - path: "dist/*.whl"
            label: "Wheel Package"
          - path: "dist/*.tar.gz"
            label: "Source Package"

    - "@semantic-release/changelog"

    - "semantic-release-pypi"

    - - "@semantic-release/git":
      - assets:
          - "pyproject.toml"
