site_name: QueryGuard - A guard against unruly sql
site_url: https://queryguard.readthedocs.io/
nav:
  - Home: index.md
  - Usage: usage.md
  - Rules: rules.md
theme: readthedocs
plugins:
  - mkdocstrings:
      default_handler: python
