name: Release

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release
    environment: release
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.7.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to GitHub Release
        uses: python-semantic-release/upload-to-gh-release@main
        if: ${{ steps.release.outputs.released }} == 'true' && startsWith(github.ref, 'refs/tags')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
